#!/usr/bin/env python2.7
import _bw

#_bw.getrp('test/test.bw', 'test/test_tss.bed', 'test/out.tab', 10000.0, 0, 0)
_bw.getrp('/data5/DC_results/Result_new3/dataset53709/53709_treat.bw', 'test/hg38.tss', 'test/out.tab', 10000.0, -1000, 1000)
#_bw.getrp('test/42359_treat.bw', 'test/hg38.tss', 'test/out.tab', 10000.0)
